# Build the Hex Forge knob sprite as a horizontal filmstrip (N square frames) that
# MOD's film-knob widget indexes by value. Two modes:
#   1. --src knob-top.png : rotate a supplied TOP-VIEW knob image (pointer at 12
#      o'clock, transparent bg, square) into the strip. Use this to drop in a
#      photoreal knob (e.g. generated by an image model) with guaranteed
#      frame-to-frame consistency.
#   2. no --src : draw a procedural amp-style knob. The body shading is radially
#      SYMMETRIC (so rotating the whole image doesn't move the highlight — only the
#      pointer appears to turn), giving a clean, consistent interim knob.
# Output: lv2/modgui-hexforge/knobs/knob.png  (frames*F wide, F tall).
import os, sys, argparse, numpy as np
from PIL import Image

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT  = os.path.join(REPO, "lv2", "modgui-hexforge", "knobs", "knob.png")

def procedural_knob(hr):
    """Render one top-view knob (pointer up) at hr x hr, RGBA float 0..1."""
    yy, xx = np.mgrid[0:hr, 0:hr].astype(np.float64)
    cx = cy = (hr - 1) / 2.0
    x = (xx - cx) / (hr / 2.0)          # -1..1
    y = (yy - cy) / (hr / 2.0)
    r = np.sqrt(x * x + y * y)
    ang = np.arctan2(x, -y)             # 0 at 12 o'clock, +CW

    R_out, R_body = 0.94, 0.72          # skirt outer / body radius (in -1..1)
    rgb = np.zeros((hr, hr, 3))
    a   = np.zeros((hr, hr))

    # --- metallic skirt ring (radially symmetric: rotation-invariant) ---
    skirt = (r <= R_out)
    ring_t = np.clip((r - R_body) / (R_out - R_body), 0, 1)   # 0 inner .. 1 outer
    metal = 0.46 - 0.22 * ring_t                              # darker toward rim
    grooves = 0.055 * np.cos(ang * 60.0)                      # fine knurling ticks
    metal = np.clip(metal + grooves, 0, 1)
    for c in range(3):
        rgb[..., c] = np.where(skirt, metal * (1.06 if c == 2 else 1.0), rgb[..., c])
    a = np.where(skirt, 1.0, a)

    # --- domed body (symmetric radial shading = convex look, rotation-safe) ---
    body = (r <= R_body)
    rb = np.clip(r / R_body, 0, 1)
    dome = np.sqrt(np.clip(1.0 - rb * rb, 0, 1))              # 1 center .. 0 edge
    shade = 0.05 + 0.19 * dome                                # dark glossy plastic dome
    body_rgb = np.stack([shade * 0.94, shade * 0.97, shade * 1.12], -1)
    for c in range(3):
        rgb[..., c] = np.where(body, body_rgb[..., c], rgb[..., c])
    # crisp glossy rim highlight near the body edge (symmetric → rotation-safe)
    spec = np.exp(-((rb - 0.80) ** 2) / (2 * 0.004)) * 0.22
    rgb += (spec[..., None] * body[..., None])
    # bevel highlight where body meets skirt
    bevel = np.exp(-((r - R_body) ** 2) / (2 * 0.0016))
    rgb += (bevel * 0.20)[..., None] * body[..., None]

    # --- pointer: bright indicator from center to top edge (the ONE rotating cue) ---
    px = np.abs(x)
    pointer = (y < 0) & (px < 0.075) & (r < R_body * 0.98) & (r > 0.10)
    tip = np.exp(-((r - R_body * 0.9) ** 2) / (2 * 0.02)) * ((px < 0.12) & (y < 0))
    rgb = np.where(pointer[..., None], np.array([0.90, 0.91, 0.95]), rgb)
    rgb += (tip[..., None] * 0.10)

    # --- anti-aliased outer alpha edge ---
    edge = np.clip((R_out - r) / (2.0 / hr * 2.0), 0, 1)
    a = np.maximum(a, 0) * edge
    a = np.where(r <= R_out, np.maximum(a, edge), a)

    out = np.dstack([np.clip(rgb, 0, 1), np.clip(a, 0, 1)])
    return (out * 255).astype(np.uint8)

def load_src(path, hr):
    im = Image.open(path).convert("RGBA")
    if im.size != (hr, hr):
        im = im.resize((hr, hr), Image.LANCZOS)
    return im

def build(frames, frame_px, sweep_deg, src):
    hr = frame_px * 3                                  # supersample for smooth edges
    base = load_src(src, hr) if src else Image.fromarray(procedural_knob(hr), "RGBA")
    strip = Image.new("RGBA", (frame_px * frames, frame_px), (0, 0, 0, 0))
    for i in range(frames):
        ang = -sweep_deg / 2.0 + sweep_deg * (i / (frames - 1))   # frame0=min .. last=max
        rot = base.rotate(-ang, resample=Image.BICUBIC, expand=False)   # -ang: CW for +value
        rot = rot.resize((frame_px, frame_px), Image.LANCZOS)
        strip.paste(rot, (i * frame_px, 0), rot)
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    strip.save(OUT)
    print("wrote", OUT, strip.size, "(%d frames of %dpx)" % (frames, frame_px))

if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", default=None, help="top-view knob PNG (pointer up); omit for procedural")
    ap.add_argument("--frames", type=int, default=101)
    ap.add_argument("--frame-px", type=int, default=128)
    ap.add_argument("--sweep", type=float, default=300.0, help="total rotation degrees")
    args = ap.parse_args()
    build(args.frames, args.frame_px, args.sweep, args.src)
